In [1]:
import sframe as sf
import pandas as pd

In [15]:
cluster_9 = pd.read_csv('Clusters_model20/cluster_9.csv')
cluster_9

,X1,file_name,category,text,recommendations
0,50,training-dataset/engineering/1404.txt,engineering,Relocatable vs Position Independent Code or ...,[50 1177 1310 954 1051 720 463 957 933 805 136]
1,136,training-dataset/engineering/220.txt,engineering,Consistent Hashing carlosgaldinoConsistent H...,[136 933 1177 1199 50 805 463 720 1051 1310 1130]
2,383,training-dataset/engineering/1106.txt,engineering,Performance Usage at Instagram Instagram E...,[383 1310 1353 1130 463 933 1177 1051 954 1060...
3,463,training-dataset/engineering/1499.txt,engineering,Code Generation The Inner Sanctum of Database...,[463 1051 805 50 1310 933 1177 383 1353 1130 1...
4,720,training-dataset/engineering/1481.txt,engineering,Efficient storage how we went down from 50 PB...,[720 805 50 1051 933 1177 1130 957 1310 136 383]
5,805,training-dataset/engineering/1221.txt,engineering,Why Uber Engineering Switched from Postgres to...,[805 720 463 1177 933 1051 50 1310 1130 136 1060]
6,933,training-dataset/engineering/748.txt,engineering,Real time Deduping At Scale Tapjoy Engineeri...,[933 1353 1177 136 805 720 463 1051 50 1310 954]
7,954,training-dataset/engineering/680.txt,engineering,Swapping memory limits and cgroupsThis week ...,[954 1177 50 1310 957 1353 1051 1130 933 463 383]
8,957,training-dataset/engineering/671.txt,engineering,Things to learn about LinuxI asked on Twitter ...,[957 1177 954 50 1310 1051 1353 720 1130 933 805]
9,1051,training-dataset/engineering/1306.txt,engineering,Pyflame Uber Engineering s Ptracing Profiler ...,[1051 1310 50 1177 463 720 933 805 957 954 1060]
10,1060,training-dataset/engineering/1502.txt,engineering,Rewriting Uber Engineering s Android Rider App...,[1060 1177 1310 1353 805 1051 463 933 383 50 1...
11,1130,training-dataset/product/265.txt,product,User Memory Design How To Design For Experien...,[1130 1353 1177 383 954 805 1310 463 720 933 50]
12,1177,training-dataset/engineering/642.txt,engineering,How much memory is my process using I often wa...,[1177 50 954 1310 957 1051 1353 933 805 463 720]
13,1199,training-dataset/engineering/881.txt,engineering,Fast Multi GPU collectives with NCCLToday many...,[1199 136 933 463 805 1051 50 1177 1310 1060 1...
14,1310,training-dataset/engineering/1009.txt,engineering,Dismissing Python Garbage Collection at Instag...,[1310 1177 1051 50 954 463 1060 383 957 1353 933]
15,1312,training-dataset/engineering/324.txt,engineering,Learn Enough Git to Be DangerousGet access to ...,[1312 1177 957 1199 136 1060 463 1130 805 1353...
16,1353,training-dataset/engineering/1127.txt,engineering,Reducing Slack s memory footprint Several Pe...,[1353 1177 933 954 1130 383 1310 50 957 1060 463]

In [14]:
cluster_8= pd.read_csv('Clusters_model20/cluster_8.csv')
cluster_8

,X1,file_name,category,text,recommendations
0,30,training-dataset/business/406.txt,business,The One Secret to a Successful Startup Focus ...,[30 122 377 147 626 603 133 937 619 1172 1258]
1,53,training-dataset/business/1008.txt,business,How to Build a Startup Ecosystem in Your CityS...,[53 496 133 626 377 746 611 122 147 619 603]
2,122,training-dataset/business/1186.txt,business,Creating an Elevator Pitch that Attracts Inves...,[122 626 265 377 746 611 147 710 133 603 30]
3,133,training-dataset/business/1096.txt,business,How to Build a Global CompanyJust about every ...,[133 53 377 122 603 147 496 30 626 1110 710]
4,147,training-dataset/business/1234.txt,business,Unconventional Methods for Building a Startup ...,[147 377 626 1076 1172 122 603 746 1110 930 937]
5,265,training-dataset/business/702.txt,business,Perfect Your Elevator Pitch with the Pyramid P...,[265 122 1203 626 377 835 611 147 710 1258 1208]
6,268,training-dataset/business/604.txt,business,2 excuses startups should never useSize doesn ...,[268 611 1258 710 486 626 1076 759 147 1208 569]
7,292,training-dataset/business/862.txt,business,If You re Thinking About Raising Money For You...,[292 759 626 611 122 377 569 603 710 147 1110]
8,377,training-dataset/business/492.txt,business,Are You Starting a Company in 2017 Begin Here...,[377 147 122 835 626 133 603 1172 1110 746 30]
9,474,training-dataset/business/1177.txt,business,7 Effective Tools to Solve Your Startup Proble...,[474 1076 626 147 611 1208 746 377 937 1110 1172]
10,486,training-dataset/business/312.txt,business,Joining a Startup The MacroWe ve recruited a...,[486 816 710 569 626 611 958 1258 1208 603 746]
11,491,training-dataset/business/1244.txt,business,What really defines a growth team There s this...,[491 754 1203 1110 486 1258 611 710 133 958 569]
12,496,training-dataset/business/416.txt,business,How to Launch a Startup in EuropeIn recent yea...,[496 53 133 603 377 147 626 122 474 710 1110]
13,534,training-dataset/business/1192.txt,business,Co founder conflictHere s how it felt in the w...,[534 569 486 1258 626 1208 611 603 710 377 958]
14,546,training-dataset/business/154.txt,business,Organic Startup Ideas Want to start a s...,[546 611 1258 759 569 746 122 710 626 486 1208]
15,569,training-dataset/business/1124.txt,business,Jessica Livingston s Pretty Complete List on H...,[569 1258 611 958 759 486 754 710 626 546 377]
16,603,training-dataset/business/1014.txt,business,How to Create the Perfect Cofounder Agreement ...,[603 626 147 377 133 122 1172 937 30 759 619]
17,611,training-dataset/business/818.txt,business,How to Get Startup Ideas Want to start ...,[611 546 1258 746 759 569 626 710 1208 122 958]
18,619,training-dataset/business/431.txt,business,Don t Make This Mistake When Pivoting Your Sta...,[619 1203 626 1172 377 122 603 1076 53 30 133]
19,626,training-dataset/business/769.txt,business,How to Embrace Failure as You Transition from ...,[626 122 746 1172 147 611 377 1110 1208 603 937]
20,651,training-dataset/business/527.txt,business,Books for founders at each stage of a startup ...,[651 626 1208 1110 710 619 1172 147 746 759 1076]
21,710,training-dataset/business/86.txt,business,Why not to do a startupThe Pmarca Guide to Sta...,[710 816 611 759 1258 486 122 569 626 1208 937]
22,746,training-dataset/business/391.txt,business,3 Steps to Find Amazing Company Ideas The best...,[746 611 626 122 147 377 1208 768 53 546 486]
23,754,training-dataset/business/1490.txt,business,Before GrowthWe tell startups all the time tha...,[754 759 1258 569 491 958 1203 611 1110 710 937]
24,759,training-dataset/business/113.txt,business,Startup advice brieflyThis is a very short su...,[759 1258 611 754 569 958 710 626 1076 546 937]
25,768,training-dataset/business/299.txt,business,Users You Don t Want The MacroMichael Seibel...,[768 1258 611 746 958 569 759 1203 147 626 937]
26,816,training-dataset/business/775.txt,business,So you want to work for a startupRecently I v...,[816 710 486 626 759 122 1208 611 1258 603 569]
27,819,training-dataset/business/1295.txt,business,Don t accelerate your startup Signal v Nois...,[819 611 710 746 122 759 491 626 1258 754 569]
28,835,training-dataset/business/1026.txt,business,18 Short Simple Lessons Every Entrepreneur A...,[835 377 1110 958 626 1208 122 611 1258 937 147]
29,930,training-dataset/business/365.txt,business,3 Steps to Finding the Biggest Risks to Your S...,[930 147 626 377 1172 746 1076 133 122 1110 603]
30,937,training-dataset/business/496.txt,business,204 Startup Failure Post MortemsNo survivorshi...,[937 626 147 710 1258 1076 603 958 759 1208 611]
31,958,training-dataset/business/1091.txt,business,11 big mistakes startups should avoid or die ...,[958 1258 569 759 611 626 1110 486 754 937 377]
32,1076,training-dataset/business/302.txt,business,A Dozen Lessons about Minimum Viable Products ...,[1076 147 626 474 759 937 710 1258 1208 569 1110]
33,1110,training-dataset/business/986.txt,business,Turning Your Startup into a BusinessIn this gu...,[1110 626 147 958 377 491 937 122 835 133 1203]
34,1172,training-dataset/business/384.txt,business,Don t Build a Business Unless You re Ready to ...,[1172 626 147 619 377 603 958 930 611 569 937]
35,1203,training-dataset/business/608.txt,business,The Startup Pivot PyramidIn 2011 we raised 2M...,[1203 619 265 491 958 1110 754 1208 1076 937 626]
36,1208,training-dataset/business/284.txt,business,My Startup Generated Almost 2 Million Dollars ...,[1208 626 611 710 746 937 1258 486 759 816 1076]
37,1258,training-dataset/business/1323.txt,business,Do Things that Don t Scale Want to star...,[1258 611 569 759 958 546 754 768 710 937 626]
38,1325,training-dataset/business/486.txt,business,Why Acceptance of Failure is Critical to Start...,[1325 710 1208 486 626 569 147 930 937 1172 611]